// CheckinCollectTest.cpp — tier-2 tests of the BN→Ghidra diff path:
// storeCheckinState (baseline) + BN-side edits → collectCheckinChanges must
// produce exactly the expected GhidraCheckinPreview, including from a view
// reopened out of a .bndb.

#include "BnViewFixture.h"
#include "GhidraConnection.h"
#include "SyncEngine.h"
#include <gtest/gtest.h>
#include <cstdio>

using namespace BinaryNinja;
using namespace bn_fixture;

namespace {

constexpr uint64_t kBase = kDefaultBase;

class CheckinCollectTest : public ::testing::Test {
protected:
    void SetUp() override {
        BN_REQUIRE_CORE();
        view = makeView();
        ASSERT_TRUE(view);
    }
    void TearDown() override {
        GhidraConnection::instance().clearCheckinState();
        if (view) closeView(view);
    }

    Ref<Function> makeFunc(uint64_t va) {
        view->CreateUserFunction(view->GetDefaultPlatform(), va);
        view->UpdateAnalysisAndWait();
        for (auto& f : view->GetAnalysisFunctionsForAddress(va))
            if (f->GetStart() == va) return f;
        return nullptr;
    }

    // Import @p data into the view and seed the singleton's baseline maps —
    // the exact sequence the production import path runs.
    SyncResult importAndStore(const GhidraDbExport& data) {
        SyncResult r = SyncEngine::applyToView(view, data);
        view->UpdateAnalysisAndWait();
        GhidraConnection::instance().storeCheckinState(
            r.addrToKey, r.addrToOriginalName, r.addrToCommentKey,
            r.addrToOriginalComment, r.addrToOriginalFuncComment,
            r.addrToCommentField, r.ghidraDataTypes, r.parameters, r.bookmarks,
            r.dataItems, r.equates, r.funcSigs, r.imageBase,
            "testrepo", "/", "testitem");
        return r;
    }

    GhidraCheckinPreview collect() {
        view->UpdateAnalysisAndWait();
        return GhidraConnection::instance().collectCheckinChanges(view);
    }

    static GhidraSymbol sym(int64_t key, const std::string& name, uint64_t addr,
                            GhidraSymbolType type = GhidraSymbolType::Label) {
        GhidraSymbol s;
        s.key    = key;
        s.name   = name;
        s.addr   = addr;
        s.type   = type;
        s.source = GhidraSymbolSource::User;
        return s;
    }

    Ref<BinaryView> view;
};

// ---------------------------------------------------------------------------
// Symbols
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, NoEdits_EmptyPreview) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(1, "orig_func", kBase + kOffFuncRet,
                               GhidraSymbolType::Function));
    importAndStore(data);

    GhidraCheckinPreview preview = collect();
    EXPECT_TRUE(preview.empty());
}

TEST_F(CheckinCollectTest, SymbolRename_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(42, "orig_func", kBase + kOffFuncRet,
                               GhidraSymbolType::Function));
    importAndStore(data);

    view->DefineUserSymbol(new Symbol(FunctionSymbol, "renamed_func",
                                      kBase + kOffFuncRet));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.renames.size(), 1u);
    EXPECT_EQ(preview.renames[0].key, 42);
    EXPECT_EQ(preview.renames[0].originalName, "orig_func");
    EXPECT_EQ(preview.renames[0].newName, "renamed_func");
    EXPECT_TRUE(preview.newSymbols.empty());
}

TEST_F(CheckinCollectTest, SymbolRenameBack_NoOp) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(42, "orig_func", kBase + kOffFuncRet,
                               GhidraSymbolType::Function));
    importAndStore(data);

    view->DefineUserSymbol(new Symbol(FunctionSymbol, "temp", kBase + kOffFuncRet));
    view->DefineUserSymbol(new Symbol(FunctionSymbol, "orig_func", kBase + kOffFuncRet));
    GhidraCheckinPreview preview = collect();
    EXPECT_TRUE(preview.renames.empty());
}

TEST_F(CheckinCollectTest, NewSymbol_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    view->DefineUserSymbol(new Symbol(DataSymbol, "brand_new_label",
                                      kBase + kOffDataStr));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.newSymbols.size(), 1u);
    EXPECT_EQ(preview.newSymbols[0].addr, kBase + kOffDataStr);
    EXPECT_EQ(preview.newSymbols[0].name, "brand_new_label");
    EXPECT_FALSE(preview.newSymbols[0].isFunction);
}

TEST_F(CheckinCollectTest, AutoGeneratedName_NotQueuedAsNewSymbol) {
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    char autoName[32];
    snprintf(autoName, sizeof(autoName), "sub_%llx",
             (unsigned long long)(kBase + kOffFuncNoRet));
    view->DefineUserSymbol(new Symbol(FunctionSymbol, autoName,
                                      kBase + kOffFuncNoRet));
    GhidraCheckinPreview preview = collect();
    EXPECT_TRUE(preview.newSymbols.empty());
}

TEST_F(CheckinCollectTest, UnicodeSymbolName_RoundTrips) {
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    view->DefineUserSymbol(new Symbol(DataSymbol, "π_данные_名前",
                                      kBase + kOffDataStr));
    GhidraCheckinPreview preview = collect();
    ASSERT_EQ(preview.newSymbols.size(), 1u);
    EXPECT_EQ(preview.newSymbols[0].name, "π_данные_名前");
}

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, CommentEdit_CarriesEncodedKey) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment c;
    c.addr       = kBase + kOffFuncEquate;
    c.eol        = "imported text";
    c.encodedKey = "0x2000000010";
    data.comments.push_back(c);
    importAndStore(data);

    view->SetCommentForAddress(kBase + kOffFuncEquate, "edited text");
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.comments.size(), 1u);
    EXPECT_EQ(preview.comments[0].addr, kBase + kOffFuncEquate);
    EXPECT_EQ(preview.comments[0].text, "edited text");
    EXPECT_EQ(preview.comments[0].encodedKey, "0x2000000010");
}

TEST_F(CheckinCollectTest, NewComment_NoKey) {
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    view->SetCommentForAddress(kBase + kOffDataInt, "fresh comment");
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.comments.size(), 1u);
    EXPECT_EQ(preview.comments[0].text, "fresh comment");
    EXPECT_TRUE(preview.comments[0].encodedKey.empty());
}

TEST_F(CheckinCollectTest, UnchangedComment_NotQueued) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment c;
    c.addr = kBase + kOffFuncEquate;
    c.eol  = "same text";
    data.comments.push_back(c);
    importAndStore(data);

    GhidraCheckinPreview preview = collect();
    EXPECT_TRUE(preview.comments.empty());
}

TEST_F(CheckinCollectTest, FunctionComment_Detected) {
    Ref<Function> func = makeFunc(kBase + kOffFuncRet);
    ASSERT_TRUE(func);
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    func->SetComment("new plate text");
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.comments.size(), 1u);
    EXPECT_EQ(preview.comments[0].addr, kBase + kOffFuncRet);
    EXPECT_EQ(preview.comments[0].text, "new plate text");
}

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, DataTypeAdd_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    importAndStore(data);

    StructureBuilder sb;
    sb.AddMemberAtOffset(Type::IntegerType(4, true), "x", 0);
    sb.AddMemberAtOffset(Type::IntegerType(4, true), "y", 4);
    view->DefineUserType(QualifiedName("BnNewStruct"),
                         Type::StructureType(sb.Finalize()));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.dataTypeChanges.size(), 1u);
    const auto& ch = preview.dataTypeChanges[0];
    EXPECT_EQ(ch.op, "add");
    EXPECT_EQ(ch.kind, "struct");
    EXPECT_EQ(ch.name, "BnNewStruct");
    EXPECT_EQ(ch.ghidraId, 0);
    ASSERT_EQ(ch.members.size(), 2u);
    EXPECT_EQ(ch.members[1].name, "y");
    EXPECT_EQ(ch.members[1].offset, 4);
}

TEST_F(CheckinCollectTest, DataTypeUpdate_DetectedWithGhidraId) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id = 77; dt.kind = "struct"; dt.name = "Point"; dt.size = 8;
    dt.members.push_back({0, 0, "x", "", 4, 0, "int32_t"});
    dt.members.push_back({4, 0, "y", "", 4, 1, "int32_t"});
    data.dataTypes.push_back(dt);
    importAndStore(data);

    // Rename member y → why.
    StructureBuilder sb;
    sb.AddMemberAtOffset(Type::IntegerType(4, true), "x", 0);
    sb.AddMemberAtOffset(Type::IntegerType(4, true), "why", 4);
    view->DefineUserType(QualifiedName("Point"),
                         Type::StructureType(sb.Finalize()));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.dataTypeChanges.size(), 1u);
    EXPECT_EQ(preview.dataTypeChanges[0].op, "update");
    EXPECT_EQ(preview.dataTypeChanges[0].ghidraId, 77);
}

TEST_F(CheckinCollectTest, DataTypeDelete_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id = 88; dt.kind = "struct"; dt.name = "Doomed"; dt.size = 4;
    dt.members.push_back({0, 0, "v", "", 4, 0, "int32_t"});
    data.dataTypes.push_back(dt);
    importAndStore(data);

    // Ghidra-imported types are registered in the auto type table (SyncEngine
    // uses DefineType with a generated id), so deletion goes through the
    // auto-type id — UndefineUserType would be a no-op here.
    std::string typeId = view->GetTypeId(QualifiedName("Doomed"));
    ASSERT_FALSE(typeId.empty());
    view->UndefineType(typeId);
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.dataTypeChanges.size(), 1u);
    EXPECT_EQ(preview.dataTypeChanges[0].op, "delete");
    EXPECT_EQ(preview.dataTypeChanges[0].name, "Doomed");
    EXPECT_EQ(preview.dataTypeChanges[0].ghidraId, 88);
}

// ---------------------------------------------------------------------------
// Bookmarks
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, BookmarkAddAndDelete_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraBookmark bm;
    bm.type = "Note"; bm.addr = kBase + kOffDataInt;
    bm.category = "old"; bm.comment = "existing";
    data.bookmarks.push_back(bm);
    importAndStore(data);

    // Add a new tag …
    Ref<TagType> tt = view->GetTagType("Ghidra: Note");
    ASSERT_TRUE(tt);
    view->CreateUserDataTag(kBase + kOffDataStr, tt, "[fresh] added note", false);
    // … and delete the imported one.
    for (auto& tag : view->GetUserDataTags(kBase + kOffDataInt))
        view->RemoveUserDataTag(kBase + kOffDataInt, tag);

    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.bookmarkChanges.size(), 2u);
    const GhidraCheckinPreview::BookmarkChange* add = nullptr;
    const GhidraCheckinPreview::BookmarkChange* del = nullptr;
    for (const auto& b : preview.bookmarkChanges) {
        if (b.op == "add")    add = &b;
        if (b.op == "delete") del = &b;
    }
    ASSERT_TRUE(add);
    EXPECT_EQ(add->type, "Note");
    EXPECT_EQ(add->addr, kBase + kOffDataStr);
    EXPECT_EQ(add->category, "fresh");
    EXPECT_EQ(add->comment, "added note");
    ASSERT_TRUE(del);
    EXPECT_EQ(del->addr, kBase + kOffDataInt);
}

// ---------------------------------------------------------------------------
// Data items
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, DataItemAddAndDelete_Detected) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id = 100; dt.kind = "struct"; dt.name = "Point"; dt.size = 8;
    dt.members.push_back({0, 0, "x", "", 4, 0, "int32_t"});
    dt.members.push_back({4, 0, "y", "", 4, 1, "int32_t"});
    data.dataTypes.push_back(dt);
    GhidraDataItem item;
    item.addr = kBase + kOffDataPoint;
    item.typeId = 100;
    data.dataItems.push_back(item);
    importAndStore(data);

    // Add a new typed data var …
    Ref<Type> pointType = view->GetTypeByName(QualifiedName("Point"));
    ASSERT_TRUE(pointType);
    view->DefineUserDataVariable(kBase + kOffDataInt,
                                 Confidence<Ref<Type>>(pointType, 255));
    // … and remove the imported one.
    view->UndefineUserDataVariable(kBase + kOffDataPoint);

    GhidraCheckinPreview preview = collect();

    const GhidraCheckinPreview::DataItemChange* add = nullptr;
    const GhidraCheckinPreview::DataItemChange* del = nullptr;
    for (const auto& d : preview.dataItemChanges) {
        if (d.op == "add")    add = &d;
        if (d.op == "delete") del = &d;
    }
    ASSERT_TRUE(add);
    EXPECT_EQ(add->addr, kBase + kOffDataInt);
    ASSERT_TRUE(del);
    EXPECT_EQ(del->addr, kBase + kOffDataPoint);
}

// ---------------------------------------------------------------------------
// Function signatures
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, ReturnTypeChange_Detected) {
    Ref<Function> func = makeFunc(kBase + kOffFuncRet);
    ASSERT_TRUE(func);

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(9, "sig_func", kBase + kOffFuncRet,
                               GhidraSymbolType::Function));
    GhidraFuncSig sig;
    sig.key = 9;
    sig.returnTypeName = "void";
    data.funcSigs.push_back(sig);
    importAndStore(data);

    func->SetReturnType(Confidence<Ref<Type>>(Type::IntegerType(8, false), 255));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.funcSigChanges.size(), 1u);
    EXPECT_EQ(preview.funcSigChanges[0].key, 9);
    EXPECT_EQ(preview.funcSigChanges[0].returnTypeName, "uint64_t");
}

// ---------------------------------------------------------------------------
// Equates
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, EquateRename_Detected) {
    Ref<Function> func = makeFunc(kBase + kOffFuncEquate);
    ASSERT_TRUE(func);

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraEquate eq;
    eq.id = 5; eq.name = "OLD_NAME"; eq.value = 500;
    eq.refs.push_back({kBase + kOffFuncEquate, 1});
    data.equates.push_back(eq);
    importAndStore(data);

    // Rename the equate's single enum member (same stable type id).
    EnumerationBuilder eb;
    eb.AddMemberWithValue("NEW_NAME", 500);
    view->DefineType("ghidra_eq_5", QualifiedName("OLD_NAME"),
                     Type::EnumerationType(eb.Finalize(), 4, false));
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.equateRenames.size(), 1u);
    EXPECT_EQ(preview.equateRenames[0].id, 5);
    EXPECT_EQ(preview.equateRenames[0].name, "NEW_NAME");
}

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, ParamRename_Detected) {
    Ref<Function> func = makeFunc(kBase + kOffFuncFrame);
    ASSERT_TRUE(func);
    auto params = func->GetParameterVariables().GetValue();
    if (params.empty())
        GTEST_SKIP() << "BN analysis found no parameters for frame function";

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(20, "frame_func", kBase + kOffFuncFrame,
                               GhidraSymbolType::Function));
    GhidraParameter p;
    p.key      = 200;
    p.funcAddr = kBase + kOffFuncFrame;
    p.name     = "count";
    p.isParam  = true;
    p.ordinal  = 0;
    p.typeName = "int32_t";
    data.parameters.push_back(p);
    importAndStore(data);

    params = func->GetParameterVariables().GetValue();
    ASSERT_FALSE(params.empty());
    func->CreateUserVariable(params[0], func->GetVariableType(params[0]),
                             "renamed_count");
    GhidraCheckinPreview preview = collect();

    ASSERT_EQ(preview.paramRenames.size(), 1u);
    EXPECT_EQ(preview.paramRenames[0].key, 200);
    EXPECT_EQ(preview.paramRenames[0].name, "renamed_count");
}

// ---------------------------------------------------------------------------
// Preview stability across .bndb save/reopen
// ---------------------------------------------------------------------------

TEST_F(CheckinCollectTest, PreviewFromReopenedBndb_MatchesLivePreview) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(sym(42, "orig_func", kBase + kOffFuncRet,
                               GhidraSymbolType::Function));
    GhidraComment c;
    c.addr       = kBase + kOffFuncEquate;
    c.eol        = "imported";
    c.encodedKey = "0x2000000010";
    data.comments.push_back(c);
    importAndStore(data);

    // Pending edits the user made before closing BN.
    view->DefineUserSymbol(new Symbol(FunctionSymbol, "renamed_func",
                                      kBase + kOffFuncRet));
    view->SetCommentForAddress(kBase + kOffFuncEquate, "edited");

    GhidraCheckinPreview live = collect();
    ASSERT_EQ(live.renames.size(), 1u);
    ASSERT_EQ(live.comments.size(), 1u);

    std::string bndb = testDataDir() + "/tmp_checkin_persist.bndb";
    Ref<BinaryView> reopened = saveAndReopen(view, bndb);
    view = nullptr;
    ASSERT_TRUE(reopened);
    reopened->UpdateAnalysisAndWait();

    // Same singleton baseline (as after a BN restart with state restored):
    // the reopened database must yield the identical preview.
    GhidraCheckinPreview persisted =
        GhidraConnection::instance().collectCheckinChanges(reopened);
    ASSERT_EQ(persisted.renames.size(), 1u);
    EXPECT_EQ(persisted.renames[0].key, live.renames[0].key);
    EXPECT_EQ(persisted.renames[0].newName, live.renames[0].newName);
    ASSERT_EQ(persisted.comments.size(), 1u);
    EXPECT_EQ(persisted.comments[0].text, live.comments[0].text);
    EXPECT_EQ(persisted.comments[0].encodedKey, live.comments[0].encodedKey);

    closeView(reopened);
    std::remove(bndb.c_str());
}

} // namespace
