// SyncEngineImportTest.cpp — tier-2 tests of the Ghidra→BN import path:
// SyncEngine::applyToView against a real headless BinaryView, one test group
// per data category, plus rebase and .bndb persistence pins.

#include "BnViewFixture.h"
#include "SyncEngine.h"
#include <gtest/gtest.h>
#include <algorithm>
#include <cstdio>

using namespace BinaryNinja;
using namespace bn_fixture;

namespace {

constexpr uint64_t kBase = kDefaultBase;

GhidraSymbol makeSymbol(int64_t key, const std::string& name, uint64_t addr,
                        GhidraSymbolType type = GhidraSymbolType::Label) {
    GhidraSymbol s;
    s.key    = key;
    s.name   = name;
    s.addr   = addr;
    s.type   = type;
    s.source = GhidraSymbolSource::User;
    return s;
}

class SyncEngineImportTest : public ::testing::Test {
protected:
    void SetUp() override {
        BN_REQUIRE_CORE();
        view = makeView();
        ASSERT_TRUE(view);
    }
    void TearDown() override {
        if (view) closeView(view);
    }

    // Create a function and wait for analysis so parameter variables and
    // function extents exist before the import runs (mirrors a real session,
    // where BN has analyzed the binary before the user imports).
    Ref<Function> makeFunc(uint64_t va) {
        view->CreateUserFunction(view->GetDefaultPlatform(), va);
        view->UpdateAnalysisAndWait();
        for (auto& f : view->GetAnalysisFunctionsForAddress(va))
            if (f->GetStart() == va) return f;
        return nullptr;
    }

    SyncResult apply(const GhidraDbExport& data) {
        SyncResult r = SyncEngine::applyToView(view, data);
        view->UpdateAnalysisAndWait();
        return r;
    }

    Ref<BinaryView> view;
};

// ---------------------------------------------------------------------------
// Symbols
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Symbols_LabelAndFunctionApplied) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(1, "my_func", kBase + kOffFuncRet,
                                      GhidraSymbolType::Function));
    data.symbols.push_back(makeSymbol(2, "my_data", kBase + kOffDataInt));

    SyncResult r = apply(data);
    EXPECT_EQ(r.symbolsApplied, 2);
    EXPECT_EQ(r.functionsCreated, 1);

    auto funcSym = view->GetSymbolByAddress(kBase + kOffFuncRet);
    ASSERT_TRUE(funcSym);
    EXPECT_EQ(funcSym->GetShortName(), "my_func");
    EXPECT_EQ(funcSym->GetType(), FunctionSymbol);

    auto dataSym = view->GetSymbolByAddress(kBase + kOffDataInt);
    ASSERT_TRUE(dataSym);
    EXPECT_EQ(dataSym->GetShortName(), "my_data");

    // A real BN function was created for the Ghidra function symbol.
    bool hasFunc = false;
    for (auto& f : view->GetAnalysisFunctionsForAddress(kBase + kOffFuncRet))
        if (f->GetStart() == kBase + kOffFuncRet) hasFunc = true;
    EXPECT_TRUE(hasFunc);

    // Write-back baseline recorded.
    EXPECT_EQ(r.addrToKey.at(kBase + kOffFuncRet), 1);
    EXPECT_EQ(r.addrToOriginalName.at(kBase + kOffFuncRet), "my_func");
}

TEST_F(SyncEngineImportTest, Symbols_PreservesUserChosenName) {
    view->DefineUserSymbol(new Symbol(DataSymbol, "user_picked_this",
                                      kBase + kOffDataInt));

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(7, "ghidra_name", kBase + kOffDataInt));
    SyncResult r = apply(data);

    auto sym = view->GetSymbolByAddress(kBase + kOffDataInt);
    ASSERT_TRUE(sym);
    EXPECT_EQ(sym->GetShortName(), "user_picked_this");
    // Ghidra's name is still the write-back baseline, so the user's name is
    // detected as a rename on the next check-in.
    EXPECT_EQ(r.addrToOriginalName.at(kBase + kOffDataInt), "ghidra_name");
}

TEST_F(SyncEngineImportTest, Symbols_OverwritesAutoGeneratedName) {
    char autoName[32];
    snprintf(autoName, sizeof(autoName), "sub_%llx",
             (unsigned long long)(kBase + kOffFuncRet));
    view->DefineUserSymbol(new Symbol(FunctionSymbol, autoName, kBase + kOffFuncRet));

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(3, "real_name", kBase + kOffFuncRet,
                                      GhidraSymbolType::Function));
    apply(data);

    auto sym = view->GetSymbolByAddress(kBase + kOffFuncRet);
    ASSERT_TRUE(sym);
    EXPECT_EQ(sym->GetShortName(), "real_name");
}

TEST_F(SyncEngineImportTest, Symbols_RebasedImport) {
    closeView(view);
    view = makeViewAt(0x140000000);
    ASSERT_TRUE(view);

    // Golden data stays in Ghidra space (base 0x400000).
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(1, "rebased_func", kBase + kOffFuncRet,
                                      GhidraSymbolType::Function));
    SyncResult r = apply(data);

    auto sym = view->GetSymbolByAddress(0x140000000 + kOffFuncRet);
    ASSERT_TRUE(sym);
    EXPECT_EQ(sym->GetShortName(), "rebased_func");
    EXPECT_EQ(r.addrToKey.count(0x140000000 + kOffFuncRet), 1u);
}

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Comments_SingleColumnRoutingRecorded) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment pre;
    pre.addr       = kBase + kOffFuncEquate;
    pre.pre        = "pre comment";
    pre.encodedKey = "0x2000000010";
    data.comments.push_back(pre);

    SyncResult r = apply(data);
    EXPECT_EQ(r.commentsApplied, 1);
    EXPECT_EQ(view->GetCommentForAddress(kBase + kOffFuncEquate), "pre comment");
    EXPECT_EQ(r.addrToCommentField.at(kBase + kOffFuncEquate), "pre");
    EXPECT_EQ(r.addrToCommentKey.at(kBase + kOffFuncEquate), "0x2000000010");
}

TEST_F(SyncEngineImportTest, Comments_MultiColumnMergedAndRoutedToEol) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment c;
    c.addr = kBase + kOffFuncEquate;
    c.eol  = "line e";
    c.pre  = "line p";
    data.comments.push_back(c);

    SyncResult r = apply(data);
    EXPECT_EQ(view->GetCommentForAddress(kBase + kOffFuncEquate), "line e\nline p");
    EXPECT_EQ(r.addrToCommentField.at(kBase + kOffFuncEquate), "eol");
}

TEST_F(SyncEngineImportTest, Comments_PlateBecomesFunctionComment) {
    Ref<Function> func = makeFunc(kBase + kOffFuncRet);
    ASSERT_TRUE(func);

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment c;
    c.addr  = kBase + kOffFuncRet;
    c.plate = "function header";
    data.comments.push_back(c);
    SyncResult r = apply(data);

    EXPECT_EQ(func->GetComment(), "function header");
    EXPECT_EQ(r.addrToOriginalFuncComment.at(kBase + kOffFuncRet),
              "function header");
}

TEST_F(SyncEngineImportTest, Comments_PreservesDifferentUserComment) {
    view->SetCommentForAddress(kBase + kOffFuncEquate, "user wrote this");

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraComment c;
    c.addr = kBase + kOffFuncEquate;
    c.eol  = "ghidra comment";
    data.comments.push_back(c);
    SyncResult r = apply(data);

    EXPECT_EQ(view->GetCommentForAddress(kBase + kOffFuncEquate),
              "user wrote this");
    // Ghidra text is the baseline → check-in will push the user's version.
    EXPECT_EQ(r.addrToOriginalComment.at(kBase + kOffFuncEquate),
              "ghidra comment");
}

// ---------------------------------------------------------------------------
// Function flags
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, FuncFlags_BecomeTags) {
    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(10, "thunk_func", kBase + kOffFuncThunk,
                                      GhidraSymbolType::Function));
    data.symbols.push_back(makeSymbol(11, "noret_func", kBase + kOffFuncNoRet,
                                      GhidraSymbolType::Function));
    GhidraFuncFlags f1; f1.key = 10; f1.thunk = true;
    GhidraFuncFlags f2; f2.key = 11; f2.noReturn = true; f2.isInline = true;
    data.funcFlags = {f1, f2};

    SyncResult r = apply(data);
    EXPECT_EQ(r.flagsApplied, 2);

    auto tagsAt = [&](uint64_t va) {
        std::vector<std::string> names;
        for (auto& f : view->GetAnalysisFunctionsForAddress(va)) {
            if (f->GetStart() != va) continue;
            for (auto& t : f->GetFunctionTags())
                names.push_back(t->GetType()->GetName());
        }
        return names;
    };
    auto thunkTags = tagsAt(kBase + kOffFuncThunk);
    EXPECT_NE(std::find(thunkTags.begin(), thunkTags.end(),
                        std::string("Ghidra: Thunk")), thunkTags.end());
    auto noretTags = tagsAt(kBase + kOffFuncNoRet);
    EXPECT_NE(std::find(noretTags.begin(), noretTags.end(),
                        std::string("Ghidra: NoReturn")), noretTags.end());
    EXPECT_NE(std::find(noretTags.begin(), noretTags.end(),
                        std::string("Ghidra: Inline")), noretTags.end());
}

// ---------------------------------------------------------------------------
// Equates
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Equates_EnumTypeAndDisplayOverride) {
    Ref<Function> func = makeFunc(kBase + kOffFuncEquate);
    ASSERT_TRUE(func);

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraEquate eq;
    eq.id    = 42;
    eq.name  = "MAX_SIZE";
    eq.value = 500;
    eq.refs.push_back({kBase + kOffFuncEquate, 1}); // mov eax, 0x1F4 — imm operand
    data.equates.push_back(eq);
    apply(data);

    Ref<Type> eqType = view->GetTypeById("ghidra_eq_42");
    ASSERT_TRUE(eqType);
    ASSERT_TRUE(eqType->IsEnumeration());
    auto members = eqType->GetEnumeration()->GetMembers();
    ASSERT_EQ(members.size(), 1u);
    EXPECT_EQ(members[0].name, "MAX_SIZE");
    EXPECT_EQ(members[0].value, 500u);

    auto [disp, dispType] = func->GetIntegerConstantDisplayTypeAndEnumType(
        func->GetArchitecture(), kBase + kOffFuncEquate, 500, 1);
    (void)dispType;
    EXPECT_EQ(disp, EnumerationDisplayType);
}

// ---------------------------------------------------------------------------
// Bookmarks
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Bookmarks_BecomeDataTags) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraBookmark bm;
    bm.type     = "Note";
    bm.addr     = kBase + kOffDataStr;
    bm.category = "review";
    bm.comment  = "look here";
    data.bookmarks.push_back(bm);
    apply(data);

    auto tags = view->GetUserDataTags(kBase + kOffDataStr);
    ASSERT_EQ(tags.size(), 1u);
    EXPECT_EQ(tags[0]->GetType()->GetName(), "Ghidra: Note");
    EXPECT_EQ(tags[0]->GetData(), "[review] look here");
}

// ---------------------------------------------------------------------------
// Parameters & locals
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Parameters_RenamedByOrdinal) {
    Ref<Function> func = makeFunc(kBase + kOffFuncFrame);
    ASSERT_TRUE(func);
    auto params = func->GetParameterVariables().GetValue();
    if (params.empty())
        GTEST_SKIP() << "BN analysis found no parameters for frame function";

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraParameter p;
    p.key      = 100;
    p.funcAddr = kBase + kOffFuncFrame;
    p.name     = "count";
    p.isParam  = true;
    p.ordinal  = 0;
    p.typeName = "int";
    data.parameters.push_back(p);
    apply(data);

    params = func->GetParameterVariables().GetValue();
    ASSERT_FALSE(params.empty());
    EXPECT_EQ(func->GetVariableName(params[0]), "count");
    auto vt = func->GetVariableType(params[0]);
    ASSERT_TRUE(vt.GetValue());
    EXPECT_EQ(vt.GetValue()->GetWidth(), 4u); // "int" → int32_t
}

TEST_F(SyncEngineImportTest, Parameters_UserNameNotOverwritten) {
    Ref<Function> func = makeFunc(kBase + kOffFuncFrame);
    ASSERT_TRUE(func);
    auto params = func->GetParameterVariables().GetValue();
    if (params.empty())
        GTEST_SKIP() << "BN analysis found no parameters for frame function";
    func->CreateUserVariable(params[0],
                             func->GetVariableType(params[0]), "user_named");
    view->UpdateAnalysisAndWait();

    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraParameter p;
    p.key      = 100;
    p.funcAddr = kBase + kOffFuncFrame;
    p.name     = "ghidra_named";
    p.isParam  = true;
    p.ordinal  = 0;
    data.parameters.push_back(p);
    apply(data);

    params = func->GetParameterVariables().GetValue();
    ASSERT_FALSE(params.empty());
    EXPECT_EQ(func->GetVariableName(params[0]), "user_named");
}

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, DataTypes_StructMembersRegistered) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id   = 100;
    dt.kind = "struct";
    dt.name = "Point";
    dt.size = 8;
    dt.members.push_back({0, 0, "x", "", 4, 0, "int"});
    dt.members.push_back({4, 0, "y", "", 4, 1, "int"});
    data.dataTypes.push_back(dt);
    apply(data);

    Ref<Type> t = view->GetTypeByName(QualifiedName("Point"));
    ASSERT_TRUE(t);
    ASSERT_TRUE(t->IsStructure());
    auto members = t->GetStructure()->GetMembers();
    ASSERT_EQ(members.size(), 2u);
    EXPECT_EQ(members[0].name, "x");
    EXPECT_EQ(members[0].offset, 0u);
    EXPECT_EQ(members[1].name, "y");
    EXPECT_EQ(members[1].offset, 4u);
    EXPECT_EQ(t->GetWidth(), 8u);
}

TEST_F(SyncEngineImportTest, DataTypes_EnumWidthsAndNegativeValue) {
    GhidraDbExport data;
    data.imageBase = kBase;
    for (int width : {1, 2, 4, 8}) {
        GhidraDataType dt;
        dt.id   = 200 + width;
        dt.kind = "enum";
        dt.name = "E" + std::to_string(width);
        dt.size = width;
        dt.values.push_back({"OK", 0, ""});
        dt.values.push_back({"NEG", -1, ""});
        data.dataTypes.push_back(dt);
    }
    apply(data);

    for (int width : {1, 2, 4, 8}) {
        Ref<Type> t = view->GetTypeByName(QualifiedName("E" + std::to_string(width)));
        ASSERT_TRUE(t) << "E" << width;
        ASSERT_TRUE(t->IsEnumeration());
        EXPECT_EQ((int)t->GetWidth(), width);
        auto vals = t->GetEnumeration()->GetMembers();
        ASSERT_EQ(vals.size(), 2u);
        EXPECT_EQ(vals[1].name, "NEG");
    }
}

TEST_F(SyncEngineImportTest, DataTypes_TypedefChainResolves) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType st;
    st.id = 300; st.kind = "struct"; st.name = "Inner"; st.size = 4;
    st.members.push_back({0, 0, "v", "", 4, 0, "int"});
    data.dataTypes.push_back(st);
    GhidraDataType td1;
    td1.id = 301; td1.kind = "typedef"; td1.name = "gh_inner_t";
    td1.underlyingTypeId = 300; td1.underlyingTypeName = "Inner"; td1.size = 4;
    data.dataTypes.push_back(td1);
    GhidraDataType td2;
    td2.id = 302; td2.kind = "typedef"; td2.name = "gh_handle_t";
    td2.underlyingTypeId = 301; td2.underlyingTypeName = "gh_inner_t"; td2.size = 4;
    data.dataTypes.push_back(td2);
    apply(data);

    Ref<Type> t = view->GetTypeByName(QualifiedName("gh_handle_t"));
    ASSERT_TRUE(t);
    ASSERT_TRUE(t->IsNamedTypeRefer());
    EXPECT_EQ(t->GetNamedTypeReference()->GetName().GetString(), "gh_inner_t");
    Ref<Type> mid = view->GetTypeByName(QualifiedName("gh_inner_t"));
    ASSERT_TRUE(mid);
    ASSERT_TRUE(mid->IsNamedTypeRefer());
    EXPECT_EQ(mid->GetNamedTypeReference()->GetName().GetString(), "Inner");
}

TEST_F(SyncEngineImportTest, DataTypes_PointerAndArrayMembers) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id = 400; dt.kind = "struct"; dt.name = "Complex"; dt.size = 24;
    dt.members.push_back({0, 0, "next", "", 8, 0, "Complex *"});
    dt.members.push_back({8, 0, "name", "", 16, 1, "char[16]"});
    data.dataTypes.push_back(dt);
    apply(data);

    Ref<Type> t = view->GetTypeByName(QualifiedName("Complex"));
    ASSERT_TRUE(t);
    ASSERT_TRUE(t->IsStructure());
    auto members = t->GetStructure()->GetMembers();
    ASSERT_EQ(members.size(), 2u);
    EXPECT_TRUE(members[0].type.GetValue()->IsPointer());
    EXPECT_TRUE(members[1].type.GetValue()->IsArray());
    EXPECT_EQ(members[1].type.GetValue()->GetElementCount(), 16u);
}

// ---------------------------------------------------------------------------
// Data items
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, DataItems_TypedVariableDefined) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraDataType dt;
    dt.id = 100; dt.kind = "struct"; dt.name = "Point"; dt.size = 8;
    dt.members.push_back({0, 0, "x", "", 4, 0, "int"});
    dt.members.push_back({4, 0, "y", "", 4, 1, "int"});
    data.dataTypes.push_back(dt);
    GhidraDataItem item;
    item.addr   = kBase + kOffDataPoint;
    item.typeId = 100;
    data.dataItems.push_back(item);
    apply(data);

    auto dataVars = view->GetDataVariables();
    auto it = dataVars.find(kBase + kOffDataPoint);
    ASSERT_NE(it, dataVars.end());
    Ref<Type> t = it->second.type.GetValue();
    ASSERT_TRUE(t);
    EXPECT_EQ(t->GetWidth(), 8u);
}

// ---------------------------------------------------------------------------
// Memory blocks
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, MemoryBlocks_SectionForMappedAndSegmentForUnmapped) {
    GhidraDbExport data;
    data.imageBase = kBase;
    GhidraMemoryBlock mapped;
    mapped.name = ".gtext"; mapped.addr = kBase; mapped.size = 0x100;
    mapped.read = true; mapped.execute = true; mapped.initialized = true;
    data.memoryBlocks.push_back(mapped);
    GhidraMemoryBlock external;
    external.name = "EXTERNAL"; external.addr = kBase + 0x100000;
    external.size = 0x40; external.read = true; external.initialized = false;
    data.memoryBlocks.push_back(external);
    GhidraMemoryBlock overlay;
    overlay.name = "ovl"; overlay.addr = kBase; overlay.size = 0x10;
    overlay.overlay = true;
    data.memoryBlocks.push_back(overlay);

    SyncResult r = apply(data);
    EXPECT_EQ(r.sectionsAdded, 2);   // overlay skipped
    EXPECT_EQ(r.segmentsAdded, 1);   // only the unmapped EXTERNAL range

    bool foundText = false, foundExternal = false, foundOverlay = false;
    for (auto& sec : view->GetSections()) {
        if (sec->GetName() == ".gtext")   foundText = true;
        if (sec->GetName() == "EXTERNAL") foundExternal = true;
        if (sec->GetName() == "ovl")      foundOverlay = true;
    }
    EXPECT_TRUE(foundText);
    EXPECT_TRUE(foundExternal);
    EXPECT_FALSE(foundOverlay);
    EXPECT_TRUE(view->GetSegmentAt(kBase + 0x100000));
}

// ---------------------------------------------------------------------------
// Function signatures
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, FuncSigs_ReturnTypeAppliedAndCcAccepted) {
    Ref<Function> func = makeFunc(kBase + kOffFuncRet);
    ASSERT_TRUE(func);

    std::string curCC;
    {
        auto cc = func->GetCallingConvention();
        if (cc.GetValue()) curCC = cc.GetValue()->GetName();
    }

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(10, "sig_func", kBase + kOffFuncRet,
                                      GhidraSymbolType::Function));
    GhidraFuncSig sig;
    sig.key = 10;
    // CC import is applied at "imported" confidence (128), which BN's own
    // confident platform default outranks — so an alternate CC is NOT
    // guaranteed to stick. Import the current CC name (must be a clean no-op)
    // and pin the return type, which does apply.
    sig.callingConvention = curCC;
    sig.returnTypeName    = "longlong";
    data.funcSigs.push_back(sig);
    apply(data);

    auto ret = func->GetReturnType();
    ASSERT_TRUE(ret.GetValue());
    EXPECT_EQ(ret.GetValue()->GetWidth(), 8u); // longlong → int64_t
    if (!curCC.empty()) {
        auto cc = func->GetCallingConvention();
        ASSERT_TRUE(cc.GetValue());
        EXPECT_EQ(cc.GetValue()->GetName(), curCC);
    }
}

// ---------------------------------------------------------------------------
// .bndb persistence — the imported state must survive save + reopen
// ---------------------------------------------------------------------------

TEST_F(SyncEngineImportTest, Bndb_ImportedStateSurvivesSaveReopen) {
    Ref<Function> func = makeFunc(kBase + kOffFuncEquate);
    ASSERT_TRUE(func);

    GhidraDbExport data;
    data.imageBase = kBase;
    data.symbols.push_back(makeSymbol(1, "persisted_func", kBase + kOffFuncEquate,
                                      GhidraSymbolType::Function));
    GhidraComment c;
    c.addr = kBase + kOffFuncEquate;
    c.eol  = "persisted comment";
    data.comments.push_back(c);
    GhidraDataType dt;
    dt.id = 100; dt.kind = "struct"; dt.name = "Persisted"; dt.size = 4;
    dt.members.push_back({0, 0, "v", "", 4, 0, "int"});
    data.dataTypes.push_back(dt);
    GhidraDataItem item;
    item.addr = kBase + kOffDataPoint;
    item.typeId = 100;
    data.dataItems.push_back(item);
    GhidraBookmark bm;
    bm.type = "Note"; bm.addr = kBase + kOffDataStr;
    bm.category = "cat"; bm.comment = "bm";
    data.bookmarks.push_back(bm);
    apply(data);

    std::string bndb = testDataDir() + "/tmp_import_persist.bndb";
    Ref<BinaryView> reopened = saveAndReopen(view, bndb);
    view = nullptr; // original closed by saveAndReopen
    ASSERT_TRUE(reopened);

    auto sym = reopened->GetSymbolByAddress(kBase + kOffFuncEquate);
    ASSERT_TRUE(sym);
    EXPECT_EQ(sym->GetShortName(), "persisted_func");
    EXPECT_EQ(reopened->GetCommentForAddress(kBase + kOffFuncEquate),
              "persisted comment");
    Ref<Type> t = reopened->GetTypeByName(QualifiedName("Persisted"));
    ASSERT_TRUE(t);
    EXPECT_TRUE(t->IsStructure());
    auto dataVars = reopened->GetDataVariables();
    EXPECT_NE(dataVars.find(kBase + kOffDataPoint), dataVars.end());
    auto tags = reopened->GetUserDataTags(kBase + kOffDataStr);
    ASSERT_EQ(tags.size(), 1u);
    EXPECT_EQ(tags[0]->GetData(), "[cat] bm");

    closeView(reopened);
    std::remove(bndb.c_str());
}

} // namespace
